import turtle
tn = turtle.Turtle()
def t_la(tn, sz):
    tn.pensize(7)
    tn.left(90)
    tn.backward(sz)
    tn.left(90)
    tn.forward(50)
    tn.left(90)
    tn.backward(sz)
def t_tar(tn, sz):
    tn.pensize(7)
    tn.left(90)
    tn.backward(sz)
    tn.left(90)
    tn.forward(sz)
    tn.left(60)
    tn.forward(100)
def s_ta(tn, dz):
    tn.left(90)
    tn.penup()
    tn.backward(dz)
    tn.pendown()
def t_ji():
    tn.pensize(7)
    tn.left(30)
    tn.forward(40)
    tn.right(60)
    tn.forward(80)
    tn.right(150)
    tn.forward(120)
    tn.left(60)
    tn.forward(80)
    tn.right(60)
    tn.forward(80)
    tn.right(90)
    tn.forward(80)
def n_ta():
    tn.fillcolor("black")
    tn.begin_fill()
    tn.circle(5)
    tn.end_fill()

la = t_la(tn, 100)
space = s_ta(tn, 40)
tar = t_tar(tn, 50)
ss = s_ta(tn, 80)
tn.left(120)
tn.penup()
tn.forward(70)
tn.right(90)
tn.pendown()
ji = t_ji()
tn.penup()
tn.right(90)
tn.forward(290)
tn.pendown()
dot = n_ta()
tn.penup()
tn.backward(10)
tn.pendown()
dot = n_ta()
space = s_ta(tn, 80)
tn.left(90)
tn.penup()
tn.forward(100)
tn.pendown()
dot = n_ta()

turtle.mainloop()